### PR TITLE
Upgrade Ruby, add Gemfile and fix Rubocop offenses

### PR DESCRIPTION
**Pull request by corny**

### CODE REVIEW

**Comment by SamSaffron** [comment]
Looks pretty safe to me, we usually base our docker files off 2.6 these days not 2.7, also we don't really use alpine that much anymore. 

@mpalmer  you happy with merging this, I guess we can adjust the dockerfile after the merge.

**Comment by corny** [comment]
Thanks for your feedback. I changed the Ruby version to 2.6.

**Comment by SamSaffron** [comment]
Sorry, do you mind submitting a new on (upgrading to 2.7) this is conflicting big time now.

**Comment by corny** [comment]
done: #9

**Pull request closed without merging**
